service: ecommerce-api

provider:
  name: aws
  runtime: nodejs22.x

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  products:
    handler: handler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true

  cart:
    handler: handler.addToCart
    events:
      - http:
          path: cart
          method: post
          cors: true

  getCart:
    handler: handler.getCart
    events:
      - http:
          path: cart
          method: get
          cors: true
  
  removeFromCart:
    handler: handler.removeFromCart
    events:
      - http:
          path: cart
          method: delete
          cors: true

  checkout:
    handler: handler.checkout
    events:
      - http:
          path: checkout
          method: post
          cors: true
  
  register:
    handler: utils/auth.register
    events:
      - http:
          path: register
          method: post
          cors: true

  orders:
    handler: handler.getUserOrders
    events:
      - http:
          path: orders
          method: get
          cors: true        

plugins:
  - serverless-offline